/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */
library lib_test_server_route;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:i_redis/i_redis.dart';
import 'package:sqljocky/sqljocky.dart';
import 'package:logging/logging.dart';
import 'package:i_dart/i_dart_srv.dart';

part './i_config/server_route.dart';

// .pub
// model
// store
// route
part './route/test_route_logic.dart';
