name: test_server_store
description: Description
dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  sqljocky: ">=0.11.0 <0.12.0"
  logging: ">=0.9.2 <0.10.0"
  http_server: ">=0.9.3 <0.10.0"
  route: ">=0.4.6 <0.5.0"
  i_redis: ">=1.0.3 <2.0.0"
  uuid: ">=0.4.1 <0.5.0"
  i_dart: ">=0.1.0 <0.5.0"
