name: i_dart
version: 0.1.1
authors:
- ila <himulawang@gmail.com>
homepage: https://github.com/himulawang/i_dart
description: ParaNoidz I Framework for Dart
environment:
  sdk: ">=1.7.0"
dependencies:
  logging: ">=0.9.2 <0.10.0"
  args: ">=0.12.0+2 <0.13.0"
