name: i_dart
description: ParaNoidz I Framework for Dart
dependencies:
  unittest: any
  sqljocky: any
  lawndart: any
  http: any
  logging: any
  http_server: any
  route: any
  i_redis: any
  paper_elements: any
  stream: any
  uuid: ">=0.4.1 <0.5.0"
  args: ">=0.12.0+2 <0.13.0"
