/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */


part of lib_test_model;

class RoomList extends IList {
  static String _delimiter = ':';
  RoomList(id) { _initPK([id]); }

  RoomList.filledMap(id, Map dataList) {
    _initPK([id]);

    dataList.forEach((String i, Room model) {
      if (model is! Room) return;
      rawSet(model);
    });
  }

  RoomList.filledList(id, List dataList) {
    _initPK([id]);

    dataList.forEach((Room model) {
      if (model is! Room) return;
      rawSet(model);
    });
  }

  _initPK(List pk) => pks = pk;

  setPK(id) => pks = [id];
  String getUnitedPK() {
    if (pks.contains(null)) throw new IModelException(10021);
    return pks.join(_delimiter);
  }

  Room get(name) => list["${name}"];

  void fromList(List dataList, [bool changeUpdatedList = false]) {
    if (dataList is! List) throw new IModelException(10012, [this.runtimeType]);

    dataList.forEach((List data) {
      Room model = new Room();
      model.fromList(data, changeUpdatedList);
      if (changeUpdatedList) {
        if (get(model.getUnitedChildPK()) == null) {
          add(model);
        } else {
          set(model);
        }
      } else {
        rawSet(model);
      }
    });
  }
  void fromFull(Map dataList, [bool changeUpdatedList = false]) {
    if (dataList is! Map) throw new IModelException(10013, [this.runtimeType]);

    dataList.forEach((String i, Map data) {
      Room model = new Room();
      model.fromFull(data, changeUpdatedList);
      if (changeUpdatedList) {
        if (get(model.getUnitedChildPK()) == null) {
          add(model);
        } else {
          set(model);
        }
      } else {
        rawSet(model);
      }
    });
  }
  void fromAbb(Map dataList, [bool changeUpdatedList = false]) {
    if (dataList is! Map) throw new IModelException(10014, [this.runtimeType]);

    dataList.forEach((String i, Map data) {
      Room model = new Room();
      model.fromAbb(data, changeUpdatedList);
      if (changeUpdatedList) {
        if (get(model.getUnitedChildPK()) == null) {
          add(model);
        } else {
          set(model);
        }
      } else {
        rawSet(model);
      }
    });
  }
}
