/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */
library lib_test_client_route;

import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'dart:indexed_db';
import 'dart:html';

import 'package:logging/logging.dart';
import 'package:i_dart/i_dart_clt.dart';

part './i_config/client_route.dart';

// .pub
// model
// store
// route
part './route/example_route_logic.dart';
