/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */


part of lib_test_server_store;

class MultipleListStore {
  static Future set(MultipleList list) {
    return MultipleListMariaDBStore.set(list)
    .then((_) => MultipleListRedisStore.set(list))
    .then((MultipleList list) => list..resetAllToList())
    ;
  }

  static Future get(id, name) {
    return MultipleListRedisStore.get(id, name)
    .then((MultipleList list) {
      if (list.isExist()) return list;
      return MultipleListMariaDBStore.get(id, name);
    })
    ;
  }

  static Future del(MultipleList list) {
    return MultipleListMariaDBStore.del(list)
    .then((_) => MultipleListRedisStore.del(list))
    ;
  }
}
