/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */


part of lib_test_server_store;

class RoomStore {
  static Future add(Room model) {
    return RoomMariaDBStore.add(model)
    .then((_) => RoomRedisStore.add(model))
    .then((Room model) => model..setUpdatedList(false))
    ;
  }

  static Future set(Room model) {
    return RoomMariaDBStore.set(model)
    .then((_) => RoomRedisStore.set(model))
    .then((Room model) => model..setUpdatedList(false))
    ;
  }

  static Future get(id) {
    return RoomRedisStore.get(id)
    .then((Room model) {
      if (model.isExist()) return model;
      return RoomMariaDBStore.get(id);
    })
    ;
  }

  static Future del(Room model) {
    return RoomMariaDBStore.del(model)
    .then((_) => RoomRedisStore.del(model))
    ;
  }
}
