/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */


part of lib_test_server_store;

class UserSingleNoExpireListStore {
  static Future set(UserSingleNoExpireList list) {
    return UserSingleNoExpireListMariaDBStore.set(list)
    .then((_) => UserSingleNoExpireListRedisStore.set(list))
    .then((UserSingleNoExpireList list) => list..resetAllToList())
    ;
  }

  static Future get(id) {
    return UserSingleNoExpireListRedisStore.get(id)
    .then((UserSingleNoExpireList list) {
      if (list.isExist()) return list;
      return UserSingleNoExpireListMariaDBStore.get(id);
    })
    ;
  }

  static Future del(UserSingleNoExpireList list) {
    return UserSingleNoExpireListMariaDBStore.del(list)
    .then((_) => UserSingleNoExpireListRedisStore.del(list))
    ;
  }
}
