/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */


part of lib_test_server_store;

class UserForeverStore {
  static Future add(UserForever model) {
    return UserForeverMariaDBStore.add(model)
    .then((_) => UserForeverRedisStore.add(model))
    .then((UserForever model) => model..setUpdatedList(false))
    ;
  }

  static Future set(UserForever model) {
    return UserForeverMariaDBStore.set(model)
    .then((_) => UserForeverRedisStore.set(model))
    .then((UserForever model) => model..setUpdatedList(false))
    ;
  }

  static Future get(id) {
    return UserForeverRedisStore.get(id)
    .then((UserForever model) {
      if (model.isExist()) return model;
      return UserForeverMariaDBStore.get(id);
    })
    ;
  }

  static Future del(UserForever model) {
    return UserForeverMariaDBStore.del(model)
    .then((_) => UserForeverRedisStore.del(model))
    ;
  }
}
