/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */


part of lib_test_server_store;

class UserSingleListStore {
  static Future set(UserSingleList list) {
    return UserSingleListMariaDBStore.set(list)
    .then((_) => UserSingleListRedisStore.set(list))
    .then((UserSingleList list) => list..resetAllToList())
    ;
  }

  static Future get(id) {
    return UserSingleListRedisStore.get(id)
    .then((UserSingleList list) {
      if (list.isExist()) return list;
      return UserSingleListMariaDBStore.get(id);
    })
    ;
  }

  static Future del(UserSingleList list) {
    return UserSingleListMariaDBStore.del(list)
    .then((_) => UserSingleListRedisStore.del(list))
    ;
  }
}
