/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */


part of lib_test_server_store;

class UserToSetLengthZeroStore {
  static Future add(UserToSetLengthZero model) {
    return UserToSetLengthZeroMariaDBStore.add(model)
    .then((_) => UserToSetLengthZeroRedisStore.add(model))
    .then((UserToSetLengthZero model) => model..setUpdatedList(false))
    ;
  }

  static Future set(UserToSetLengthZero model) {
    return UserToSetLengthZeroMariaDBStore.set(model)
    .then((_) => UserToSetLengthZeroRedisStore.set(model))
    .then((UserToSetLengthZero model) => model..setUpdatedList(false))
    ;
  }

  static Future get(id) {
    return UserToSetLengthZeroRedisStore.get(id)
    .then((UserToSetLengthZero model) {
      if (model.isExist()) return model;
      return UserToSetLengthZeroMariaDBStore.get(id);
    })
    ;
  }

  static Future del(UserToSetLengthZero model) {
    return UserToSetLengthZeroMariaDBStore.del(model)
    .then((_) => UserToSetLengthZeroRedisStore.del(model))
    ;
  }
}
