/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */


part of lib_test_server_store;

class UserMultiStore {
  static Future add(UserMulti model) {
    return UserMultiMariaDBStore.add(model)
    .then((_) => UserMultiRedisStore.add(model))
    .then((UserMulti model) => model..setUpdatedList(false))
    ;
  }

  static Future set(UserMulti model) {
    return UserMultiMariaDBStore.set(model)
    .then((_) => UserMultiRedisStore.set(model))
    .then((UserMulti model) => model..setUpdatedList(false))
    ;
  }

  static Future get(id, name, uniqueName) {
    return UserMultiRedisStore.get(id, name, uniqueName)
    .then((UserMulti model) {
      if (model.isExist()) return model;
      return UserMultiMariaDBStore.get(id, name, uniqueName);
    })
    ;
  }

  static Future del(UserMulti model) {
    return UserMultiMariaDBStore.del(model)
    .then((_) => UserMultiRedisStore.del(model))
    ;
  }
}
