/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */


part of lib_test_server_store;

class UserStore {
  static Future add(User model) {
    return UserMariaDBStore.add(model)
    .then((_) => UserRedisStore.add(model))
    .then((User model) => model..setUpdatedList(false))
    ;
  }

  static Future set(User model) {
    return UserMariaDBStore.set(model)
    .then((_) => UserRedisStore.set(model))
    .then((User model) => model..setUpdatedList(false))
    ;
  }

  static Future get(id) {
    return UserRedisStore.get(id)
    .then((User model) {
      if (model.isExist()) return model;
      return UserMariaDBStore.get(id);
    })
    ;
  }

  static Future del(User model) {
    return UserMariaDBStore.del(model)
    .then((_) => UserRedisStore.del(model))
    ;
  }
}
