/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */

part of lib_test;

class UserSingleListRedisStore extends IRedisStore {
  static const Map store = const {"type":"redis","readWriteSeparate":false,"shardMethod":"CRC32","master":"GameCache","slave":"GameCacheSlave","expire":86400,"mode":"Atom"};
  static const String abb = 'us';

  static const String _typeDelimiter = '_';
  static const String _fieldDelimiter = '-';
  static const String _keyDelimiter = ':';

  static Future set(UserSingleList list) {
    if (list is! UserSingleList) throw new IStoreException(20040);

    if (!list.isUpdated()) {
      new IStoreException(25009);
      Completer completer = new Completer();
      completer.complete(list);
      return completer.future;
    }

    IRedis handler = new IRedisHandlerPool().getWriteHandler(store, list);
    String listKey = _makeListKey(list);

    List waitList = [];

    list.getToAddList().forEach((String childId, UserSingle model) {
      String childKey = _makeChildKey(list, model);
      waitList..add(_addChild(childKey, model))
        ..add(handler.sadd(listKey, childKey).catchError(_handleErr));
    });

    list.getToSetList().forEach((String childId, UserSingle model) {
      String childKey = _makeChildKey(list, model);
      waitList.add(_setChild(childKey, model));
    });

    list.getToDelList().forEach((String childId, UserSingle model) {
      String childKey = _makeChildKey(list, model);
      waitList..add(_delChild(childKey, model))
        ..add(handler.srem(listKey, childId.toString()).catchError(_handleErr));
    });

    // TODO judge if list has expireTime in ListStoreMaker
    // if this list is new, we set expireTime
    // otherwise, we use get function to set expireTime
    if (!list.isExist())  waitList.add(handler.expire(listKey, 86400));

    return Future.wait(waitList)
    .then((_) => list..resetAllToList())
    .catchError(_handleErr);
  }

  static Future get(id) {
    UserSingleList list = new UserSingleList(id);

    IRedis handler = new IRedisHandlerPool().getReaderHandler(store, list);
    String listKey = _makeListKey(list);

    return handler.smembers(listKey)
    .then((List result) {
      if (result.length == 0) throw new IStoreException(25008);

      List waitList = [];
      result.forEach((String childKey) {
        UserSingle model = new UserSingle();
        IRedis childHandler = new IRedisHandlerPool().getReaderHandler(store, model);

        waitList.add(
          handler.exists(childKey)
          .then((int exists) {
            if (exists == 0) throw new IStoreException(25003);
            return handler.hmget(childKey, new List.from(model.getMapAbb().keys));
          })
          .then((List data) {
            model..fromList(data)..setExist();
            list._set(model);
          })
          .catchError((e) {
            if (e is IStoreException && e.code == 25003) return model;
            throw e;
          })
        );
      });

      return Future.wait(waitList).then((_) => list..setExist());
    })
    .catchError((e) {
      if (e is IStoreException && e.code == 25008) return list;
      throw e;
    });
  }

  static Future del(UserSingleList list) {
    if (list is! UserSingleList) throw new IStoreException(20038);
    num id = list.getPK();
    if (id is! num) throw new IStoreException(20039);

    IRedis handler = new IRedisHandlerPool().getWriteHandler(store, list);
    String abbListKey = _makeListKey(list);

    List waitList = [];
    list.getList().forEach((num childId, UserSingle model) {
      waitList.add(UserSingleRedisStore.del(model));
    });

    waitList.add(handler.del(abbListKey));

    return Future.wait(waitList)
    .catchError(_handleErr);
  }

  static Future _addChild(String key, UserSingle model) {
    Map toAddAbb = model.toAddAbb(true);
    if (toAddAbb.length == 0) throw new IStoreException(20032);

    IRedis handler = new IRedisHandlerPool().getWriteHandler(store, model);

    return handler.exists(key)
    .then((int exists) {
      if (exists == 1) throw new IStoreException(20024);
      return handler.hmset(key, toAddAbb);
    })
    .then((String result) {
      if (result != 'OK') throw new IStoreException(20025);
      return handler.expire(key, 86400);
    })
    .then((int result) {
      if (result == 1) return model;
      new IStoreException(25004);
      return model;
    })
    .catchError(_handleErr);
  }

  static Future _setChild(String key, UserSingle model) {
    Map toSetAbb = model.toSetAbb(true);
    if (toSetAbb.length == 0) {
      new IStoreException(25001);
      Completer completer = new Completer();
      completer.complete(model);
      return completer.future;
    }

    IRedis handler = new IRedisHandlerPool().getWriteHandler(store, model);

    return handler.exists(key)
    .then((int exists) {
      if (exists == 0) throw new IStoreException(20028);
      return handler.hmset(key, toSetAbb);
    })
    .then((String result) {
      if (result != 'OK') throw new IStoreException(20029);
      return handler.expire(key, 86400);
    })
    .then((int result) {
      if (result == 1) return model;
      new IStoreException(25010);
      return model;
    })
    .catchError(_handleErr);
  }

  static Future _delChild(String key, UserSingle model) {
    IRedis handler = new IRedisHandlerPool().getWriteHandler(store, model);

    return handler.del(key)
    .then((num deletedNum) {
      if (deletedNum == 0) new IStoreException(25002);
      return deletedNum;
    })
    .catchError(_handleErr);
  }

  static String _makeListKey(UserSingleList list)
    => '${abb}${_typeDelimiter}l${_fieldDelimiter}${list.getPK().join(_keyDelimiter)}';

  static String _makeChildKey(UserSingleList list, UserSingle model)
    => '${abb}${_typeDelimiter}c${_fieldDelimiter}${list.getPK().join(_keyDelimiter)}${_fieldDelimiter}${model.getChildPK().join(_keyDelimiter)}';

  static void _handleErr(e) => throw e;
}
