/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */
library lib_test_client_store;

import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'dart:indexed_db';
import 'dart:html';

import 'package:logging/logging.dart';
import 'package:i_dart/i_dart_clt.dart';

part './i_config/client_route.dart';
part './i_config/orm.dart';
part './i_config/store.dart';
part './i_config/idb_upgrade.dart';

// model
part './model/user_single_list.dart';
part './model/single_list.dart';
part './model/user_multi_list.dart';
part './model/user_multi_pk.dart';
part './model/user_multi.dart';
part './model/user_single_to_add_length_zero.dart';
part './model/single.dart';
part './model/user_single_pk.dart';
part './model/user_single_to_set_length_zero.dart';
part './model/multiple_list.dart';
part './model/multiple.dart';
part './model/user_single.dart';
// store
part './store/user_single_to_set_length_zero_idb_store.dart';
part './store/multiple_list_idb_store.dart';
part './store/single_list_idb_store.dart';
part './store/user_single_idb_store.dart';
part './store/user_single_to_add_length_zero_idb_store.dart';
part './store/user_multi_pk_idb_store.dart';
part './store/user_multi_idb_store.dart';
part './store/user_single_pk_idb_store.dart';
// route
part './route/example_route_logic.dart';
