/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */

class IModelException extends IException {
  static final Map _CODES = {
    //'10001': '',
    //'10002': '',
    '10003': 'Model exists when add model to list.',
    '10004': 'Model not exist when del model from list.',
    '10005': 'Model not exist when update model to list.',
    '10006': 'Invalid input data when fromList for model: %%, input args length: %%, which expect: %%.',
    '10007': 'Invalid input data when fromAbb for model: %%, input args length: %%, which expect: %%.',
    '10008': 'Invalid input data when fromFull for model: %%, input args length: %%, which expect: %%.',
    '10009': 'Invalid input args length when construct model: %%, input args length: %%, which expect: %%.',
    '10010': 'Invalid input args type when construct model: %%, args: %%.',
    '10011': 'Invalid pk when initialize list.',
    '10012': 'Invalid datas when fromList for list: %%.',
    '10013': 'Invalid datas when fromFull for list: %%.',
    '10014': 'Invalid datas when fromAbb for list: %%.',
    '10015': 'PK is not set.',
    '10016': 'Multiple PK is not fully set: %%.',
    //'10017': '',
    '10018': 'Multiple ChildPK is not fully set: %%.',
    '10019': 'Multiple WholePK is not fully set: %%.',
    '10020': 'Multiple ListPK is not fully set: %%.',
    '10021': 'List pk is not fully set: %%.',
  };

  IModelException(int inputCode, [List inputParameters]) {
    super.shout(inputCode, inputParameters, _CODES);
  }
}