/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */

part of i_dart;

class IPK {
  num pk;
  bool _updated = false;

  void set(num v) {
    pk = v;
    _updated = true;
  }
  
  num get() => pk;

  num incr([num step = 1]) {
    pk += step;
    _updated = true;
    return pk;
  }
  
  void reset() => set(0);

  bool setUpdated(bool flag) => _updated = flag;
  bool isUpdated() => _updated;
}